### ISSUE TITLE
[Mac] Improve instructions for getting nv to work with mlcuddidl

### ISSUE THREAD

**Issue by alberdingk-thijm** [princedpw/nv#7]
I've had issues trying to get nv to compile on my Mac due apparently to the [`mlcuddidl`](https://opam.ocaml.org/packages/mlcuddidl/) package.

There are some problems with the opam package as found in the opam repository, which would be good to have described somewhere. If anyone has a diff of how they were able to get nv to compile with `mlcuddidl` v 3.0.4, that would also be useful for future users.

EDIT:

Here's the TL;DR of how to install `mlcuddidl.3.0.4` for compatibility with `nv`:
```
opam source mlcuddidl.3.0.4 --dir "$YOUR_SRC_DIR"
cd "$YOUR_SRC_DIR/mlcuddidl.3.0.4"
make distclean # just to be safe
./configure --disable-profiling
make
make install
```

Trying to do this more directly with `opam-source` followed by `opam pin .` seems to give me `inconsistent assumptions over interface Cudd` errors, so I'm afraid for now it's best to just suffer with mlcuddidl outside opam's version control.

**Comment by alberdingk-thijm** [comment]
Some initial points. All this information is obtained from a MacBook Pro running macOS 10.14.5 with Darwin 18.6.0, with `opam switch 4.05.0`.

Attempting to simply run `opam install mlcuddidl` produces the following error, buried in the logs of `mlcuddidl`'s `configure` script:
```
...
checking whether we are cross compiling... configure: error: in `/Users/tim/.opam/4.05.0/.opam-switch/build/mlcuddidl.3.0.4/cuddsrc-prof':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
...
```

To get around this, I get the source from opam via `opam source mlcuddidl` and then perform the following steps:
```
cd mlcuddidl.3.0.4
./configure --disable-profiling
make
make install
# there is now a directory ~/.opam/4.05.0/lib/cudd
```

Disabling profiling gets us past any compilation errors and allows the build of `mlcuddidl` to complete.
However, we now obtain an error when we run `dune build src/exe/main.exe`:

```
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Cudd referenced from src/lib/lang/nv_lang.cmxa(Nv_lang__Syntax),
           src/lib/lang/nv_lang.cmxa(Nv_lang__BddUtils),
           src/lib/lang/nv_lang.cmxa(Nv_lang__BddMap),
           src/lib/lang/nv_lang.cmxa(Nv_lang__BddFunc)
```

Each listed file attempts to open the `Cudd` module. 
This suggests that ocaml cannot find the Cudd module to link.
`src/lib/lang/dune` specifies that `cudd` is a library for these files, and `dune external-lib-deps --missing src/exe/main.exe` does not report any errors.
 
Executing the following in `utop` also works:

```
#require "cudd";;
open Cudd
```

**Comment by alberdingk-thijm** [comment]
It turns out the META file that was copied into `.opam/4.05.0/lib/cudd/` was empty, which meant `ocamlfind` was not able to figure out where the `.cmxa` files were. Running `make distclean`, `make` and `make install` again appeared to have fixed the problem, oddly enough. This could be due to differences in how `sed` works between BSD and GNU: I'm not entirely sure.

**Comment by alberdingk-thijm** [comment]
See [top comment](https://github.com/princedpw/nv/issues/7#issue-477054614) for current instructions.
